### ISSUE TITLE
Using co-bcrypt is io.js

### ISSUE THREAD

**Issue by chrisveness** [rkusa/co-bcrypt#3]
co-bcrypt crashes when used with io.js (1.0.4):

    /.../node_modules/co-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:79
            throw e
                  ^
    Error: Module version mismatch. Expected 42, got 14.
        at Error (native)
        at Module.load (module.js:341:32)
        at Function.Module._load (module.js:296:12)
        at Module.require (module.js:351:17)
        at require (module.js:370:17)
        at bindings (/.../node_modules/co-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
        at Object.<anonymous> (/.../node_modules/co-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
        at Module._compile (module.js:446:26)
        at Object.Module._extensions..js (module.js:464:10)
        at Module.load (module.js:341:32)

To replicate, `# nvm install iojs` and `# node app.js`.

**Comment by rkusa** [comment]
Does [`bcrypt`](https://github.com/ncb000gt/node.bcrypt.js/issues/268) work for you? Have you installed the dependency against iojs?

**Comment by chrisveness** [comment]
What should I do to install the dependency against iojs?

**Comment by chrisveness** [comment]
I realise I can move forward by using co-bcryptjs which works with both Node.js v0.11 and io.js, so this doesn't bother me for the moment.

If you want to get co-bcrypt working with io.js, I'd be glad to help if I can, but co-bcryptjs will be fine for me for now.

**Comment by rkusa** [comment]
This is because `co-bcryptjs` does not rely on a native module, but `co-bcrypt` does. I think, iojs needs a patched npm to compile native modules against iojs instead of npm. If `bcrypt` is successfully compiled  against iojs, `co-bcrypt` should work, too.
